services:
  app:
    build:
      target: prod
      context: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: unless-stopped

  mailcatcher:
    image: sj26/mailcatcher@sha256:238a915586b99dd957fed9dfc27fa36518e038b9d43368fbaf2e384968b6e36f
    ports:
      - 1080:1080
